---
name: clinicassistant
description: This Project To Make Clicnic Assitant For Doctors and its clinics
  and help patients to reserve easily
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  android_intent_plus: ^4.0.1
  auto_size_text: ^3.0.0
  build_runner: ^2.3.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^5.0.31
  dropdown_button2: ^2.1.4
  fl_location: ^2.0.0
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_otp_text_field: ^1.1.0+2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.7.0
  google_maps_flutter: ^2.2.8
  image_picker: ^0.8.7+4
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  lottie: ^2.4.0
  responsive_framework: ^0.2.0
  shared_preferences: ^2.1.2
  shimmer: ^2.0.0
dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.2.12
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  resize_behavior: shrink_only
flutter_native_splash:
  color: '#FFFFFF'
  image: assets/images/start.jpg
  android_gravity: fill
  android: true
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
  fonts:
    - family: Arabic
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: Noto
      fonts:
        - asset: assets/fonts/noto.ttf
